travis:
  secure:
    BINSTAR_TOKEN: I6qQe7iAbYl1Ga/yTl5+4DPbDWaNVTnEUSMclchkGwTZjUdnWGNXSA4R521KgBMfaXFpdgzslx/HgBHjvxGO7MkQsYUWCGhqaCGH16iwBkYreydJGfq1ohqGan/unQE7ObVGMxw8CmJVSjgBg1eTIU0qCY++ihe9sPN3do0pMlAhVBb+KrYBecp4+dpMLtHNheoqkZGgdKwsE9VI7yf3AVFBFvR5cA6ZxHS+TpOlk+0riH8n2H4FG2CIggXYyee2b/ItTdf91YnRrNhtmmJIIgkzueeCmXFogFEV5oi7uO2r0CIA0RF2Ure6gkLCSrRmpAx12NQnJ1LhOSCqbkpR5p/csOvdIgGF8fswgDJvmuBZODBhGyrs5dy6pRS97joNzbrwT554euxzYqIW8y9Ttb+Jp9BiupKHdfpMNuHAqdOyRyXvJbU0oHV7Nneo9kwbTbJf+w1BtbGbe3GbJnsFkdENM4xt5vNPiF2xhN9rfnbEhhwrmQ7B5LejYvCylRpCu0GHBNf4MJ8BzpP4TuoiGmu5pZ0U9GWB+P4HzKF7QWYAH5t1paYFe2GNaBGFPJUXmrLNcRcRMaXojioSRJP6EDCve69noYens71bfNwXtDrfJEy+XCSY3SFLGwDnUeiUtqpvDawkeFgRh4RFPhIETgG4KvSlhZdVVGvNM5z4Efc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
